version: '3'
services:
  server:
    build: ./beeride-server
    links:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres/beeride
  postgres: 
    build: ./postgres
